# SPDX-License-Identifier: MIT
# Copyright (c) James Jenrette / 1102tools
"""Read-only access to the bundled GSA per diem snapshot.

The data files are generated by scripts/build_snapshot.py from GSA's
published rate, ZIP, and M&IE files plus Census 2020 place/county codes.
Everything here is pure lookup; no network access.
"""

from __future__ import annotations

import gzip
import json
from dataclasses import dataclass, field
from functools import lru_cache
from importlib import resources
from typing import Any

from ._geo import county_key, place_key

STANDARD = "S"  # area id for the state's standard CONUS rate


def _read(name: str) -> bytes | None:
    try:
        return resources.files(__package__).joinpath("data", name).read_bytes()
    except (FileNotFoundError, OSError):
        return None


@lru_cache(maxsize=1)
def manifest() -> dict[str, Any]:
    raw = _read("manifest.json")
    return json.loads(raw) if raw else {"fiscal_years": {}}


def available_years() -> list[int]:
    return sorted(int(y) for y in manifest().get("fiscal_years", {}))


@dataclass(frozen=True)
class Year:
    fiscal_year: int
    months: list[str]
    standard: dict[str, Any]
    destinations: dict[int, dict[str, Any]]
    state_members: dict[str, list[int]]
    zips: dict[str, list[Any]]
    county_map: dict[str, int]
    place_map: dict[str, int]
    excluded: dict[int, set[str]]
    mie_tiers: list[dict[str, float]]
    source: dict[str, Any]
    by_state_name: dict[tuple[str, str], int] = field(default_factory=dict)

    # -- areas ---------------------------------------------------------------

    def area_rate(self, area: Any, state: str) -> dict[str, Any]:
        """Uniform rate record for a destination id or the state's standard rate."""
        if area == STANDARD:
            months = self.standard["months"]
            return {
                "area_id": STANDARD,
                "destination": "Standard Rate",
                "state": state,
                "location_defined": f"All {state} locations outside a listed rate area",
                "is_standard_rate": True,
                "lodging_by_month": dict(zip(self.months, months)),
                "meals": self.standard["meals"],
            }
        d = self.destinations[int(area)]
        return {
            "area_id": d["id"],
            "destination": d["name"],
            "state": d["state"],
            "location_defined": d["location_defined"],
            "is_standard_rate": False,
            "lodging_by_month": dict(zip(self.months, d["months"])),
            "meals": d["meals"],
        }

    def zip_areas(self, zip5: str) -> list[tuple[Any, str]]:
        """(area, state) pairs GSA lists for a ZIP, in GSA file order."""
        out = []
        for entry in self.zips.get(zip5, []):
            if isinstance(entry, str):
                out.append((STANDARD, entry))
            else:
                out.append((entry, self.destinations[entry]["state"]))
        return out

    def state_destination_ids(self, state: str) -> list[int]:
        return list(self.state_members.get(state, []))

    def destination_id(self, state: str, name: str) -> int | None:
        return self.by_state_name.get((state, name))

    def area_for_county(self, state: str, county: str, place: str | None = None) -> Any | None:
        """Area for a county (plus optional place for carve-outs). None if not a county."""
        ck = county_key(state, county)
        if ck not in places():
            alt = county_key(state, county + " city")
            if alt not in places():
                return None
            ck = alt
        if place:
            pk = place_key(state, place)
            if pk in self.place_map:
                return self.place_map[pk]
        dest = self.county_map.get(ck)
        if dest is not None and place and place_key(state, place) in self.excluded.get(dest, set()):
            return None
        return dest if dest is not None else STANDARD

    def census_areas(self, state: str, place: str) -> tuple[set[Any], list[str]]:
        """Areas a Census place/town/county of this name falls in, and its counties.

        Used only to break ties among candidates GSA already returned, or to
        offer a labeled suggestion; never as an authoritative answer.
        """
        pk = place_key(state, place)
        if pk in self.place_map:
            return {self.place_map[pk]}, []
        hits = places().get(pk, [])
        if any(kind != "county" for _, kind in hits):
            hits = [h for h in hits if h[1] != "county"]
        areas: set[Any] = set()
        counties: list[str] = []
        for ck, _kind in hits:
            counties.append(ck)
            dest = self.county_map.get(ck)
            if dest is not None and pk in self.excluded.get(dest, set()):
                continue
            areas.add(dest if dest is not None else STANDARD)
        return areas, sorted(set(counties))


@lru_cache(maxsize=None)
def load_year(fiscal_year: int) -> Year | None:
    meta = manifest().get("fiscal_years", {}).get(str(fiscal_year))
    if not meta:
        return None
    raw = _read(meta["file"])
    if raw is None:
        return None
    data = json.loads(gzip.decompress(raw))
    destinations = {d["id"]: d for d in data["destinations"]}
    by_state_name = {}
    for st, ids in data["state_members"].items():
        for i in ids:
            by_state_name[(st, destinations[i]["name"])] = i
    return Year(
        fiscal_year=fiscal_year,
        months=data["months"],
        standard=data["standard"],
        destinations=destinations,
        state_members=data["state_members"],
        zips=data["zips"],
        county_map=data["county_map"],
        place_map=data["place_map"],
        excluded={int(k): set(v) for k, v in data["excluded"].items()},
        mie_tiers=data["mie_tiers"],
        source={
            "kind": "bundled_gsa_files",
            "fiscal_year": fiscal_year,
            "zip_file": meta["zip"]["url"],
            "zip_file_published": meta["zip"].get("published"),
            "zip_file_sha256": meta["zip"]["sha256"],
            "rate_file": meta["rates"]["url"],
            "mie_file": meta["mie"]["url"],
            # GSA's breakdown files are named for their first fiscal year.
            "mie_file_covers": meta["mie"].get("covers"),
        },
        by_state_name=by_state_name,
    )


@lru_cache(maxsize=1)
def places() -> dict[str, list[list[str]]]:
    raw = _read("places.json.gz")
    return json.loads(gzip.decompress(raw)) if raw else {}
