# SPDX-License-Identifier: MIT
# Copyright (c) James Jenrette / 1102tools
"""Read-only access to the bundled BLS OEWS database.

The data files are generated by scripts/build_oews_db.py from BLS's
published OEWS flat files (download.bls.gov/pub/time.series/oe/). The
package ships the database gzipped; the first lookup decompresses it once
into a cache directory (BLS_OEWS_DATA_DIR, or the user cache directory),
checks its SHA-256 against the manifest, and opens it read-only.
Everything here is pure lookup; no network access.
"""

from __future__ import annotations

import gzip
import hashlib
import json
import os
import shutil
import sqlite3
import tempfile
from functools import lru_cache
from importlib import resources
from pathlib import Path
from typing import Any

from platformdirs import user_cache_path

SOURCE_KIND = "bundled_bls_oews_files"
BLS_NOTICE = (
    "BLS.gov cannot vouch for the data or analyses derived from these data "
    "after the data have been retrieved from BLS.gov."
)
DATATYPES = tuple(f"{i:02d}" for i in range(1, 18))


class SnapshotError(RuntimeError):
    """The bundled database is missing or does not match its manifest."""


def _read(name: str) -> bytes | None:
    try:
        return resources.files(__package__).joinpath("data", name).read_bytes()
    except (FileNotFoundError, OSError):
        return None


@lru_cache(maxsize=1)
def manifest() -> dict[str, Any]:
    raw = _read("manifest.json")
    if not raw:
        raise SnapshotError("The bundled OEWS manifest (data/manifest.json) is missing.")
    return json.loads(raw)


def data_year() -> str:
    return str(manifest()["data_year"])


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _cache_dir() -> Path:
    configured = os.environ.get("BLS_OEWS_DATA_DIR", "").strip()
    return Path(configured) if configured else user_cache_path("bls-oews-mcp")


@lru_cache(maxsize=1)
def database_path() -> Path:
    """Decompress the bundled database once and return its verified path."""
    meta = manifest()
    expected = meta["database_sha256"]
    target = _cache_dir() / f"oews-{meta['data_year']}-{expected[:16]}.sqlite"
    if target.exists() and target.stat().st_size == meta["database_bytes"] and _sha256(target) == expected:
        return target
    packaged = resources.files(__package__).joinpath("data", meta["file"])
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(prefix=".oews-", suffix=".tmp", dir=target.parent)
        tmp = Path(tmp_name)
        try:
            with os.fdopen(fd, "wb") as out, packaged.open("rb") as raw, gzip.GzipFile(fileobj=raw) as gz:
                shutil.copyfileobj(gz, out, 1 << 20)
            actual = _sha256(tmp)
            if actual != expected:
                raise SnapshotError(
                    f"The bundled OEWS database does not match its manifest "
                    f"(expected {expected[:12]}, got {actual[:12]}). Reinstall bls-oews-mcp."
                )
            # Public data: readable by any user (a container prepares it at
            # build time as root and serves it as an unprivileged user).
            tmp.chmod(0o644)
            tmp.replace(target)
        finally:
            tmp.unlink(missing_ok=True)
    except (FileNotFoundError, OSError) as e:
        raise SnapshotError(f"Could not prepare the bundled OEWS database: {e}") from e
    return target


@lru_cache(maxsize=1)
def _connection() -> sqlite3.Connection:
    path = database_path()
    return sqlite3.connect(f"file:{path}?mode=ro&immutable=1", uri=True, check_same_thread=False)


def verify() -> None:
    """Raise SnapshotError unless the bundled database is present and intact."""
    database_path()
    rows = _connection().execute("SELECT value FROM meta WHERE name = 'release_code'").fetchone()
    if not rows or rows[0] != manifest()["release"]["code"]:
        raise SnapshotError("The bundled OEWS database release does not match its manifest.")


@lru_cache(maxsize=1)
def footnotes() -> dict[str, str]:
    return dict(_connection().execute("SELECT footnote_code, footnote_text FROM footnote"))


def lookup(series_ids: list[str]) -> dict[str, tuple[str, list[dict[str, str]]] | None]:
    """Return {series_id: (value, footnotes)} for each 25-character series ID.

    None means the bundled release has no estimate for that series (an
    unknown code, or a cell BLS does not publish at that level). Values are
    the strings BLS publishes, including "-" for unreleased cells.
    """
    out: dict[str, tuple[str, list[dict[str, str]]] | None] = {sid: None for sid in series_ids}
    by_key: dict[str, list[str]] = {}
    for sid in series_ids:
        if len(sid) == 25 and sid[23:] in DATATYPES:
            by_key.setdefault(sid[:23], []).append(sid)
    if not by_key:
        return out
    con = _connection()
    notes = footnotes()
    keys = list(by_key)
    for start in range(0, len(keys), 500):
        chunk = keys[start:start + 500]
        cur = con.execute(
            f"SELECT * FROM cell WHERE key IN ({','.join('?' * len(chunk))})", chunk
        )
        columns = [c[0] for c in cur.description]
        for row in cur:
            record = dict(zip(columns, row))
            for sid in by_key[record["key"]]:
                dt = sid[23:]
                value = record[f"v{dt}"]
                if value is None:
                    continue
                codes = [c.strip() for c in (record[f"f{dt}"] or "").split(",") if c.strip()]
                out[sid] = (value, [{"code": c, "text": notes.get(c, "")} for c in codes])
    return out


@lru_cache(maxsize=4096)
def occupation_name(code: str) -> str | None:
    row = _connection().execute(
        "SELECT occupation_name FROM occupation WHERE occupation_code = ?", (code,)
    ).fetchone()
    return row[0] if row else None


@lru_cache(maxsize=4096)
def area_name(code: str) -> str | None:
    row = _connection().execute("SELECT area_name FROM area WHERE area_code = ?", (code,)).fetchone()
    return row[0] if row else None


def source() -> dict[str, Any]:
    """The citation block attached to every data result."""
    meta = manifest()
    data = meta["sources"]["oe.data.0.Current"]
    return {
        "kind": SOURCE_KIND,
        "publisher": "U.S. Bureau of Labor Statistics, Occupational Employment and Wage Statistics",
        "data_year": meta["data_year"],
        "release": meta["release"]["description"],
        "published": data.get("last_modified"),
        "retrieved": meta["retrieved"],
        "data_file": data["url"],
        "data_file_sha256": data["sha256"],
        "tables": "https://www.bls.gov/oes/tables.htm",
        "notice": BLS_NOTICE,
    }
